# Generated by Django 6.0.7 on 2026-07-27 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Category name')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('url', models.URLField(max_length=1024, unique=True, verbose_name='Link/URL')),
                ('filter_params', models.JSONField(blank=True, default=dict, help_text='Example {"has_points_from_reviews": true, "delivery": 8}', verbose_name='Filters (JSON)')),
                ('max_pages', models.PositiveIntegerField(default=1, verbose_name='Max pages (actually endless scroll?)')),
                ('sort_by', models.CharField(blank=True, default='', max_length=50)),
                ('parse_interval', models.PositiveIntegerField(default=43200, verbose_name='parse interval at secs')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('last_parsed_at', models.DateTimeField(blank=True, null=True, verbose_name='Last time parsed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['is_active'], name='catalog_cat_is_acti_7db955_idx'), models.Index(fields=['last_parsed_at'], name='catalog_cat_last_pa_022f3c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.PositiveBigIntegerField(db_index=True, unique=True, verbose_name='SKU')),
                ('name', models.TextField(verbose_name='Name')),
                ('url', models.URLField(max_length=1024, verbose_name='Link/URL')),
                ('image_url', models.URLField(blank=True, default='', max_length=1024, verbose_name='Image (URL)')),
                ('brand', models.CharField(blank=True, default='', max_length=255, verbose_name='Brand')),
                ('seller', models.CharField(blank=True, default='', max_length=255, verbose_name='Seller')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Current price')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Full price before discounts')),
                ('discount_percent', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Discount %')),
                ('review_points', models.PositiveIntegerField(default=0, verbose_name='Bonuses 4 reviews')),
                ('real_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Real price (price-bonuses)')),
                ('points_ratio', models.FloatField(default=0.0, verbose_name='Freebie ratio (bonuses/price)')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name="User's rating")),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Review count / popularity')),
                ('stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='Stock')),
                ('delivery_date', models.CharField(blank=True, default='', max_length=64, verbose_name='Delivery date')),
                ('badge', models.CharField(blank=True, default='', max_length=128, verbose_name='Badge')),
                ('is_active', models.BooleanField(default=True, help_text='Are there still bonuses?', verbose_name='Flag for actual/outdated items')),
                ('is_purchased', models.BooleanField(default=False, help_text='Have I bought it already? Cause you can review only once', verbose_name='Flag for bought/not yet')),
                ('is_not_interested', models.BooleanField(default=False, help_text='Shit items I do not want aka black list', verbose_name='Flag for do not track (useless items)')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='First seen with bonuses')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='Last seen with bonuses')),
                ('last_price_change', models.DateTimeField(blank=True, null=True, verbose_name='Last price change datetime')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['real_price'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price without discounts')),
                ('review_points', models.PositiveIntegerField(default=0, verbose_name='Bonuses 4 reviews')),
                ('stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='Stock')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Recorded price datetime')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='catalog.product', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Price history',
                'verbose_name_plural': 'Price histories',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message text')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ParseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=16, verbose_name='Status')),
                ('pages_parsed', models.PositiveSmallIntegerField(default=0, verbose_name='Pages parsed count')),
                ('items_found', models.PositiveIntegerField(default=0, verbose_name='Items count')),
                ('items_created', models.PositiveIntegerField(default=0, verbose_name='New items found')),
                ('items_updated', models.PositiveIntegerField(default=0, verbose_name='Items updated')),
                ('items_deactivated', models.PositiveIntegerField(default=0, verbose_name='Items cancelled bonuses')),
                ('items_price_changed_count', models.PositiveIntegerField(default=0, verbose_name='Items with new prices')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error message')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Parse started')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Parse ended')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parse_logs', to='catalog.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Parse log',
                'verbose_name_plural': 'Parse logs',
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['category', '-started_at'], name='catalog_par_categor_fe512b_idx'), models.Index(fields=['status'], name='catalog_par_status_c2b841_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='catalog_pro_categor_891fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'real_price'], name='catalog_pro_is_acti_b47d22_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-points_ratio'], name='catalog_pro_points__0141ef_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-last_seen_at'], name='catalog_pro_last_se_ac8539_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['product', '-recorded_at'], name='catalog_pri_product_1f6099_idx'),
        ),
    ]
